version: "3.9"

services:
  knock-config:
    build: .
    container_name: knockknock-config
    volumes:
      - "./config:/config"
      - "./run-scripts:/app"
    command: python /app/py/gen_stanza.py  # TODO: CHANGE TO CORRECT ENTRY FILE
    secrets:
      - secret_pw

secrets:
  secret_pw:
    external: true
    name: knock.password