version: "3.9"

services:
  knock-config:
    build: .
    container_name: knockknock-config
    volumes:
      - "./config:/config"
      - "./data:/data"
      - "./run-scripts:/app"
    command: python /app/py/gen_stanza_from_config_str.py > /data/knock_config.log 2>&1
    secrets:
      - secret_pw

secrets:
  secret_pw:
    external: true
    name: kpassword